### ISSUE TITLE
Unavailable on NPM

### ISSUE THREAD

**Issue by imyelo** [kidonng/saber-plugin-medium-zoom#3]
It used to be fetchable before, but now it seems that the whole package has been unpublished. Would you mind republishing it again?

https://www.npmjs.com/saber-plugin-medium-zoom

**Comment by kidonng** [comment]
I did not expect anyone to use this anymore, it was created when I was just getting started doing JavaScript/open source, and basically left unmaintained since then. I'm glad it had been useful to others.

This plugin is no much more than:

```js
import mediumZoom from 'medium-zoom'

mediumZoom('.css-selector')
```

You don't need this plugin to use Medium Zoom. If you must, the plugin is still available from GitHub:

```
npm install kidonng/saber-plugin-medium-zoom
```
